version: '3.8'

services:
  app:
    build: .
    ports:
      - "5000:5000"
    environment:
      - MONGO_URI=mongodb+srv://buynowadmin:Enzosinger123!@buynow.fddwc.mongodb.net/?retryWrites=true&w=majority&appName=buynow
